# Generated by Django 4.2.16 on 2025-08-13 09:06

import Admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=Admin.models.user_logo_path
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=Admin.models.user_profile_image_path
            ),
        ),
    ]
