# Generated by Django 4.2.16 on 2025-08-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0002_customuser_logo_customuser_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="YoutubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_url", models.URLField(max_length=500)),
                ("video_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Education", "Education"),
                            ("Entertainment", "Entertainment"),
                            ("Music", "Music"),
                            ("Sports", "Sports"),
                            ("Technology", "Technology"),
                            ("Lifestyle", "Lifestyle"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
