# Generated by Django 4.2.16 on 2025-08-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0005_subscription_remove_usersubscription_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
