# Generated by Django 4.2.16 on 2025-08-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0006_subscription_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_active",
        ),
    ]
