# Generated by Django 4.2.16 on 2025-08-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0007_remove_subscription_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="revoke",
            field=models.BooleanField(default=False),
        ),
    ]
