# Generated by Django 4.2.16 on 2025-08-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0008_subscription_revoke"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                blank=True,
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                max_length=20,
                null=True,
            ),
        ),
    ]
